### ISSUE TITLE
Invalid sign for some api keys on getApiKeyInfo()

### ISSUE THREAD

**Issue by Raagh** [sieblyio/bybit-api#87]
Hello, I am getting invalid sign on some api keys(not all) when retrieving api key info.

```typescript
      async validateBybitAccount(bybitAPIKey: string, bybitAPISecret: string) {
        const client = new InverseClient(bybitAPIKey, bybitAPISecret, true);
    
        const data = await client.getApiKeyInfo();
    
        if (data.ret_code == 10003)
          throw new BadRequestException(ErrorCodes.InvalidAPIOrSecret);
    
        if (data.ret_code == 10004)
          this.logger.error(`error with no result for ${bybitAPIKey}`);
    
        if (data.result[0].inviter_id !== 0)
          throw new BadRequestException(ErrorCodes.InvalidUID);
      }
    }
```
I can provide you with an api key.

fails with an error code of 10004 invalid sign.

**Comment by tiagosiebler** [comment]
It's extremely curious that it only happens with some API keys... those API keys that experience this, do they fail every attempt? Do other private API calls work with those credentials or do all private API calls with those credentials fail?

If the only variable here is the API credentials it's more likely to be the credentials. It could be something wrong with the API secret, because the API key itself has a different error if that is incorrect (10003). 

It would also make sense that it's an issue with the API secret, given the error you're seeing (10004) is immediately after the 10003 API key error:
https://bybit-exchange.github.io/docs/inverse/#t-errors

Stab in the dark but another experiment could be to create new API credentials for the affected accounts and see if the issue persists. Hope that helps.

By the way, be careful posting API credentials in public even if you're having issues with them, even if you edit the post later. That information is still visible so please deactivate that API key and create a new one.

**Comment by Raagh** [comment]
Hi how are you, it is super strange but new API keys for the same account don't fix the issue. Apparently, the accounts affected changed their Bybit passwords in the last 2 days, causing their API keys to expire and they had to create a new one, since then this code started failing.

All API calls fail with these keys. For now, the only solution I could provide for them is to create a new Bybit account, which as you can imagine is not ideal, but it works.

Thanks for the warning, already did that

**Comment by Raagh** [comment]
I fixed it, it was totally my problem, sorry

**Comment by CryptoNawwa** [comment]
Hey, I just encouter the exact same problem :(

I try to call ` const result = await this.client.getApiKeyInfo();`

but all I get is :

```
{
  ret_code: 10004,
  ret_msg: 'error sign! origin_string[api_key=xxxxxxxxxxxx&recv_window=5000&timestamp=1673910685499]',
  ext_code: '',
  ext_info: '',
  result: null,
  time_now: '1673910685.749009'
}

```
